INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Ivan','Petrov','Mr.',25 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Ivan','Ivanov','Mr.',35 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Petr','Petrov','Mr.',30 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Petr','Sidorov','Mr.',20 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Pavel','Ivanov','Mr.',18 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Oleg','Pavlov','Mr.',16 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Viktor','Viktorov','Mr.',10 );
INSERT INTO PERSON(FIRSTNAME, LASTNAME, TITLE, AGE) VALUES ( 'Vasiliy','Pupkin','Mr.',10 );